// utils/countries.js
export const countries = {
  AF: "Afganistán",
  AL: "Albania",
  DE: "Alemania",
  AD: "Andorra",
  AO: "Angola",
  AG: "Antigua y Barbuda",
  SA: "Arabia Saudita",
  DZ: "Argelia",
  AR: "Argentina",
  AM: "Armenia",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaiyán",
  BS: "Bahamas",
  BD: "Bangladés",
  BB: "Barbados",
  BH: "Baréin",
  BE: "Bélgica",
  BZ: "Belice",
  BJ: "Benín",
  BY: "Bielorrusia",
  BO: "Bolivia",
  BA: "Bosnia y Herzegovina",
  BW: "Botsuana",
  BR: "Brasil",
  BN: "Brunéi",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  BT: "Bután",
  CV: "Cabo Verde",
  KH: "Camboya",
  CM: "Camerún",
  CA: "Canadá",
  QA: "Catar",
  CL: "Chile",
  CN: "China",
  CY: "Chipre",
  CO: "Colombia",
  KM: "Comoras",
  CG: "Congo",
  KR: "Corea del Sur",
  CR: "Costa Rica",
  HR: "Croacia",
  CU: "Cuba",
  DK: "Dinamarca",
  DO: "República Dominicana",
  EC: "Ecuador",
  EG: "Egipto",
  SV: "El Salvador",
  AE: "Emiratos Árabes Unidos",
  SK: "Eslovaquia",
  SI: "Eslovenia",
  ES: "España",
  US: "Estados Unidos",
  EE: "Estonia",
  ET: "Etiopía",
  PH: "Filipinas",
  FI: "Finlandia",
  FJ: "Fiyi",
  FR: "Francia",
  GA: "Gabón",
  GM: "Gambia",
  GE: "Georgia",
  GH: "Ghana",
  GD: "Granada",
  GR: "Grecia",
  GT: "Guatemala",
  GN: "Guinea",
  GQ: "Guinea Ecuatorial",
  GW: "Guinea-Bisáu",
  GY: "Guyana",
  HT: "Haití",
  HK:"Hong Kong",
  HN: "Honduras",
  HU: "Hungría",
  IN: "India",
  ID: "Indonesia",
  IQ: "Irak",
  IR: "Irán",
  IE: "Irlanda",
  IS: "Islandia",
  IL: "Israel",
  IT: "Italia",
  JM: "Jamaica",
  JP: "Japón",
  JO: "Jordania",
  KZ: "Kazajistán",
  KE: "Kenia",
  KG: "Kirguistán",
  KI: "Kiribati",
  KW: "Kuwait",
  LA: "Laos",
  LS: "Lesoto",
  LV: "Letonia",
  LB: "Líbano",
  LR: "Liberia",
  LY: "Libia",
  LI: "Liechtenstein",
  LT: "Lituania",
  LU: "Luxemburgo",
  MG: "Madagascar",
  MY: "Malasia",
  MW: "Malaui",
  MV: "Maldivas",
  ML: "Malí",
  MT: "Malta",
  MA: "Marruecos",
  MU: "Mauricio",
  MR: "Mauritania",
  MX: "México",
  MD: "Moldavia",
  MC: "Mónaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MZ: "Mozambique",
  NA: "Namibia",
  NP: "Nepal",
  NI: "Nicaragua",
  NE: "Níger",
  NG: "Nigeria",
  NO: "Noruega",
  NZ: "Nueva Zelanda",
  OM: "Omán",
  NL: "Países Bajos",
  PK: "Pakistán",
  PA: "Panamá",
  PG: "Papúa Nueva Guinea",
  PY: "Paraguay",
  PE: "Perú",
  PL: "Polonia",
  PT: "Portugal",
  GB: "Reino Unido",
  CZ: "República Checa",
  CF: "República Centroafricana",
  CD: "República Democrática del Congo",
  CI: "Costa de Marfil",
  RO: "Rumanía",
  RU: "Rusia",
  RW: "Ruanda",
  WS: "Samoa",
  KN: "San Cristóbal y Nieves",
  SM: "San Marino",
  VC: "San Vicente y las Granadinas",
  LC: "Santa Lucía",
  ST: "Santo Tomé y Príncipe",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leona",
  SG: "Singapur",
  SY: "Siria",
  SO: "Somalia",
  ZA: "Sudáfrica",
  SD: "Sudán",
  SS: "Sudán del Sur",
  SE: "Suecia",
  CH: "Suiza",
  SR: "Surinam",
  TH: "Tailandia",
  TZ: "Tanzania",
  TJ: "Tayikistán",
  TL: "Timor Oriental",
  TG: "Togo",
  TO: "Tonga",
  TT: "Trinidad y Tobago",
  TN: "Túnez",
  TM: "Turkmenistán",
  TR: "Turquía",
  TV: "Tuvalu",
  TW: "Taiwan",
  UA: "Ucrania",
  UG: "Uganda",
  UY: "Uruguay",
  UZ: "Uzbekistán",
  VE: "Venezuela",
  VN: "Vietnam",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabue",
};

export const getCountryName = (code) => countries[code?.toUpperCase()] || code;
